### ISSUE TITLE
Unable to login with Google account

### ISSUE THREAD

**Issue by Thomasdezeeuw** [atlarge-research/opendc-frontend#66]
I just tried logging on at https://opendc.org/ with Google but it failed. The login popup appears and disappears but nothing happens.

The console gave the following error:

```
Uncaught TypeError: t.getBasicProfile is not a function
    at e.value (Login.js:15)
    at google-login.js:1
    at h.o0 (cb=gapi.loaded_0:86)
    at xs (cb=gapi.loaded_0:89)
    at Wq (cb=gapi.loaded_0:89)
    at _.C.uea (cb=gapi.loaded_0:89)
    at Ap (cb=gapi.loaded_0:82)
```

**Comment by fabianishere** [comment]
Hi Thomas,

Thanks for reporting this issue.  

As reported in https://github.com/atlarge-research/opendc-web-server/issues/12, the server was not returning proper responses and this should be fixed now. 

However, I cannot reproduce the error you are getting at the moment, but I have experienced this before. From my experience, doing a hard cache reset or temporarily disabling your Adblocker might resolve the issue.

Let me know if it works for you! :)

**Comment by gandreadis** [comment]
What browser are you on, @Thomasdezeeuw?

**Comment by Thomasdezeeuw** [comment]
@gandreadis I'm using Chrome Version 70.0.3538.110 on macOS.

@fabianishere It still doesn't work, even with add-block disabled.
